# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from src.widgets import searchWidget, addWidget, removeWidget, updateWidget, see_allWidget


class Ui_MainWindow(object):
    #Functions to open widgets on button clicks
    def open_add_widget_F(self):
        self.open_add_widget = QtWidgets.QWidget()
        self.ui_form = addWidget.Ui_Form(self.open_add_widget)
        self.ui_form.setupUi(self.open_add_widget)
        self.open_add_widget.setWindowTitle("Components - Add")
        self.open_add_widget.show()

    def open_remove_widget_F(self):
        self.open_remove_widget = QtWidgets.QWidget()
        self.ui_form = removeWidget.Ui_Form(self.open_remove_widget)
        self.ui_form.setupUi(self.open_remove_widget)
        self.open_remove_widget.setWindowTitle("Components - Remove")
        self.open_remove_widget.show()

    def open_search_widget_F(self):
        self.open_search_widget = QtWidgets.QWidget()
        self.ui_form = searchWidget.Ui_Form()
        self.ui_form.setupUi(self.open_search_widget)
        self.open_search_widget.setWindowTitle("Components - Search")
        self.open_search_widget.show()

    def open_update_widget_F(self):
        self.open_update_widget = QtWidgets.QWidget()
        self.ui_form = updateWidget.Ui_Form(self.open_update_widget)
        self.ui_form.setupUi(self.open_update_widget)
        self.open_update_widget.setWindowTitle("Components - Update")
        self.open_update_widget.show()

    def open_seeAll_widget_F(self):
        self.open_seeAll_widget = QtWidgets.QWidget()
        self.ui_form = see_allWidget.Ui_Form(self.open_seeAll_widget)
        self.ui_form.setupUi(self.open_seeAll_widget)
        self.open_seeAll_widget.setWindowTitle("Components - See All")
        self.open_seeAll_widget.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(255, 330)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(-4, -8, 261, 341))
        self.backgroundLabel.setStyleSheet("QLabel#backgroundLabel{\n"
"background-image: url(:/bg-img/background.png);\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.search_Button = QtWidgets.QPushButton(self.centralwidget)
        self.search_Button.setGeometry(QtCore.QRect(50, 20, 150, 50))
        self.search_Button.setStyleSheet("QPushButton#search_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"}\n"
"QPushButton#search_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.search_Button.setObjectName("search_Button")
        self.search_Button.clicked.connect(self.open_search_widget_F)

        self.seeAll_Button = QtWidgets.QPushButton(self.centralwidget)
        self.seeAll_Button.setGeometry(QtCore.QRect(50, 80, 150, 50))
        self.seeAll_Button.setStyleSheet("QPushButton#seeAll_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"}\n"
"QPushButton#seeAll_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.seeAll_Button.setObjectName("seeAll_Button")
        self.seeAll_Button.clicked.connect(self.open_seeAll_widget_F)

        self.add_Button = QtWidgets.QPushButton(self.centralwidget)
        self.add_Button.setGeometry(QtCore.QRect(50, 140, 150, 50))
        self.add_Button.setStyleSheet("QPushButton#add_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"}\n"
"QPushButton#add_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.add_Button.setObjectName("add_Button")
        self.add_Button.clicked.connect(self.open_add_widget_F)

        self.update_Button = QtWidgets.QPushButton(self.centralwidget)
        self.update_Button.setGeometry(QtCore.QRect(50, 200, 150, 50))
        self.update_Button.setStyleSheet("QPushButton#update_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"}\n"
"QPushButton#update_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.update_Button.setObjectName("update_Button")
        self.update_Button.clicked.connect(self.open_update_widget_F)

        self.remove_Button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_Button.setGeometry(QtCore.QRect(50, 260, 150, 50))
        self.remove_Button.setStyleSheet("QPushButton#remove_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"}\n"
"QPushButton#remove_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.remove_Button.setObjectName("remove_Button")
        self.remove_Button.clicked.connect(self.open_remove_widget_F)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 255, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.statusbar.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_Button.setText(_translate("MainWindow", "Search"))
        self.seeAll_Button.setText(_translate("MainWindow", "See all"))
        self.add_Button.setText(_translate("MainWindow", "Add"))
        self.update_Button.setText(_translate("MainWindow", "Update"))
        self.remove_Button.setText(_translate("MainWindow", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
