# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCloseEvent
from PyQt5.QtWidgets import QWidget

import assets.res.background_rc
import src.db.dataBase


class Ui_Form(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

    def getData_n_AddtoDB(self):
        # Here we add the variables
        try:
            type_to_add = self.type_Add_textEdit.toPlainText()
            model_to_add = self.model_Add_textEdit.toPlainText()
            quantity_to_add = self.qt_spinBox.value()
            datasheet_to_add = self.datasheet_Add_textEdit.toPlainText()
            code_to_add = self.code_Add_textEdit.toPlainText()
            compExist = src.db.dataBase.isItInDB(type_to_add, model_to_add, code_to_add)
            if compExist:
                src.db.dataBase.updateAddFromDB(type_to_add, model_to_add, code_to_add, quantity_to_add)
            else:
                src.db.dataBase.addProduct(type_to_add, model_to_add, code_to_add, quantity_to_add,
                                           datasheet_to_add)
            self.parent().close()
        except Exception as e:
            return None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(356, 381)

        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 401, 381))
        self.backgroundLabel.setStyleSheet("QLabel#backgroundLabel{\n"
"background-image: url(:/bg-img/background.png);\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")

        self.addLabel = QtWidgets.QLabel(Form)
        self.addLabel.setGeometry(QtCore.QRect(150, 10, 51, 21))
        self.addLabel.setStyleSheet("QLabel#addLabel{\n"
"color: rgba(255,255,255,200);\n"
"font-size: 25px;\n"
"font-family: \"Arial\";\n"
"}")
        self.addLabel.setObjectName("addLabel")

        self.tip_Label = QtWidgets.QLabel(Form)
        self.tip_Label.setGeometry(QtCore.QRect(60, 60, 41, 21))
        self.tip_Label.setStyleSheet("QLabel#tip_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.tip_Label.setObjectName("tip_Label")

        self.model_Label = QtWidgets.QLabel(Form)
        self.model_Label.setGeometry(QtCore.QRect(50, 100, 51, 21))
        self.model_Label.setStyleSheet("QLabel#model_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.model_Label.setObjectName("model_Label")

        self.datasheet_Label = QtWidgets.QLabel(Form)
        self.datasheet_Label.setGeometry(QtCore.QRect(20, 220, 81, 21))
        self.datasheet_Label.setStyleSheet("QLabel#datasheet_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.datasheet_Label.setObjectName("datasheet_Label")

        self.qt_Label = QtWidgets.QLabel(Form)
        self.qt_Label.setGeometry(QtCore.QRect(30, 180, 71, 21))
        self.qt_Label.setStyleSheet("QLabel#qt_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.qt_Label.setObjectName("qt_Label")

        self.addConfirm_Button = QtWidgets.QPushButton(Form)
        self.addConfirm_Button.setGeometry(QtCore.QRect(110, 320, 131, 41))
        self.addConfirm_Button.setStyleSheet("QPushButton#addConfirm_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}\n"
"QPushButton#addConfirm_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.addConfirm_Button.setObjectName("addConfirm_Button")

        self.type_Add_textEdit = QtWidgets.QTextEdit(Form)
        self.type_Add_textEdit.setGeometry(QtCore.QRect(120, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.type_Add_textEdit.setFont(font)
        self.type_Add_textEdit.setStyleSheet("QTextEdit#type_Add_textEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"border-bottom: 2px solid white;\n"
"}")
        self.type_Add_textEdit.setObjectName("type_Add_textEdit")

        self.model_Add_textEdit = QtWidgets.QTextEdit(Form)
        self.model_Add_textEdit.setGeometry(QtCore.QRect(120, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.model_Add_textEdit.setFont(font)
        self.model_Add_textEdit.setStyleSheet("QTextEdit#model_Add_textEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"border-bottom: 2px solid white;\n"
"}")
        self.model_Add_textEdit.setObjectName("model_Add_textEdit")

        self.datasheet_Add_textEdit = QtWidgets.QTextEdit(Form)
        self.datasheet_Add_textEdit.setGeometry(QtCore.QRect(120, 220, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datasheet_Add_textEdit.setFont(font)
        self.datasheet_Add_textEdit.setStyleSheet("QTextEdit#datasheet_Add_textEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: 1px solid rgba(255,255,255,15);\n"
"border-bottom: 2px solid white;\n"
"}")
        self.datasheet_Add_textEdit.setObjectName("datasheet_Add_textEdit")

        self.qt_spinBox = QtWidgets.QSpinBox(Form)
        self.qt_spinBox.setGeometry(QtCore.QRect(120, 180, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.qt_spinBox.setFont(font)
        self.qt_spinBox.setStyleSheet("QSpinBox#qt_spinBox{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"font-size: 12px;\n"
"}")
        self.qt_spinBox.setMaximum(999)
        self.qt_spinBox.setObjectName("qt_spinBox")

        self.addLabel_2 = QtWidgets.QLabel(Form)
        self.addLabel_2.setGeometry(QtCore.QRect(310, 310, 51, 21))
        self.addLabel_2.setStyleSheet("QLabel#addLabel{\n"
"color: rgba(255,255,255,200);\n"
"font-size: 25px;\n"
"font-family: \"Arial\";\n"
"}")
        self.addLabel_2.setObjectName("addLabel_2")

        self.code_Label = QtWidgets.QLabel(Form)
        self.code_Label.setGeometry(QtCore.QRect(56, 140, 51, 21))
        self.code_Label.setStyleSheet("QLabel#code_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.code_Label.setObjectName("code_Label")

        self.code_Add_textEdit = QtWidgets.QTextEdit(Form)
        self.code_Add_textEdit.setGeometry(QtCore.QRect(120, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.code_Add_textEdit.setFont(font)
        self.code_Add_textEdit.setStyleSheet("QTextEdit#code_Add_textEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"border-bottom: 2px solid white;\n"
"}")
        self.code_Add_textEdit.setObjectName("code_Add_textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.addConfirm_Button.clicked.connect(self.getData_n_AddtoDB)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addLabel.setText(_translate("Form", "Add"))
        self.tip_Label.setText(_translate("Form", "Type"))
        self.model_Label.setText(_translate("Form", "Model"))
        self.datasheet_Label.setText(_translate("Form", "Datasheet"))
        self.qt_Label.setText(_translate("Form", "Quantity"))
        self.addConfirm_Button.setText(_translate("Form", "Add"))
        self.addLabel_2.setText(_translate("Form", "Add"))
        self.code_Label.setText(_translate("Form", "Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
