# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
import src.db.dataBase
import assets.res.background_rc

class Ui_Form(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

    def updateModels(self):
        self.model_comboBox.clear()
        selected_type = self.type_comboBox.currentText()
        models = src.db.dataBase.getMatchingModels(selected_type)
        for model in models:
            self.model_comboBox.addItem(model)
        self.model_comboBox.setCurrentText(" ")
        self.code_comboBox.setCurrentText(" ")

    def updateCodes(self):
        self.code_comboBox.clear()
        selected_type = self.type_comboBox.currentText()
        selected_model = self.model_comboBox.currentText()
        codes = src.db.dataBase.getMatchingCodes(selected_type, selected_model)
        for code in codes:
            self.code_comboBox.addItem(code)
        self.code_comboBox.setCurrentText(" ")

    def search(self):
        selected_type = self.type_comboBox.currentText()
        selected_model = self.model_comboBox.currentText()
        selected_code = self.code_comboBox.currentText()
        quantiy_n_datasheet = src.db.dataBase.searchProduct(selected_type, selected_model, selected_code)
        quantity = quantiy_n_datasheet[0][0]
        datasheet = quantiy_n_datasheet[0][1]
        self.quantity_textEdit.setText(str(quantity))
        self.datasheet_textEdit.setText(str(datasheet))

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(733, 376)

        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 741, 381))
        self.backgroundLabel.setStyleSheet("QLabel#backgroundLabel{\n"
"background-image: url(:/bg-img/background.png);\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")

        self.searchLabel = QtWidgets.QLabel(Form)
        self.searchLabel.setGeometry(QtCore.QRect(140, 10, 81, 31))
        self.searchLabel.setStyleSheet("QLabel#searchLabel{\n"
"color: rgba(255,255,255,200);\n"
"font-size: 25px;\n"
"font-family: \"Arial\";\n"
"}")
        self.searchLabel.setObjectName("searchLabel")

        self.tip_Label = QtWidgets.QLabel(Form)
        self.tip_Label.setGeometry(QtCore.QRect(30, 90, 41, 21))
        self.tip_Label.setStyleSheet("QLabel#tip_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.tip_Label.setObjectName("tip_Label")

        self.SearchConfirm_Button = QtWidgets.QPushButton(Form)
        self.SearchConfirm_Button.setGeometry(QtCore.QRect(110, 300, 131, 41))
        self.SearchConfirm_Button.setStyleSheet("QPushButton#SearchConfirm_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}\n"
"QPushButton#SearchConfirm_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.SearchConfirm_Button.setObjectName("SearchConfirm_Button")
        # When the button is clicked the search is done
        self.SearchConfirm_Button.clicked.connect(self.search)

        self.type_comboBox = QtWidgets.QComboBox(Form)
        self.type_comboBox.setGeometry(QtCore.QRect(90, 80, 221, 31))
        self.type_comboBox.setStyleSheet("QComboBox#type_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color: white;\n"
"font-size: 16px;\n"
"}")
        self.type_comboBox.setObjectName("type_comboBox")
        # Populate the type box with every unique type from db
        typesList = src.db.dataBase.getAllTypes()
        for type in typesList:
            self.type_comboBox.addItem(type)

        self.model_comboBox = QtWidgets.QComboBox(Form)
        self.model_comboBox.setGeometry(QtCore.QRect(90, 140, 221, 31))
        self.model_comboBox.setStyleSheet("QComboBox#model_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color: white;\n"
"font-size: 16px;\n"
"}")
        self.model_comboBox.setObjectName("model_comboBox")
        # Populate the model box with every model of the selected type from db
        self.type_comboBox.currentIndexChanged.connect(self.updateModels)

        self.model_label = QtWidgets.QLabel(Form)
        self.model_label.setGeometry(QtCore.QRect(20, 150, 51, 21))
        self.model_label.setStyleSheet("QLabel#model_label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.model_label.setObjectName("model_label")

        self.code_comboBox = QtWidgets.QComboBox(Form)
        self.code_comboBox.setGeometry(QtCore.QRect(90, 200, 221, 31))
        self.code_comboBox.setStyleSheet("QComboBox#code_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color: white;\n"
"font-size: 16px;\n"
"}")
        self.code_comboBox.setObjectName("code_comboBox")
        # Populate the code box with every cod of the selected type and model from db
        self.model_comboBox.currentIndexChanged.connect(self.updateCodes)

        self.code_label = QtWidgets.QLabel(Form)
        self.code_label.setGeometry(QtCore.QRect(25, 210, 51, 21))
        self.code_label.setStyleSheet("QLabel#code_label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.code_label.setObjectName("code_label")

        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(350, 0, 20, 381))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.quantity_label = QtWidgets.QLabel(Form)
        self.quantity_label.setGeometry(QtCore.QRect(400, 40, 71, 21))
        self.quantity_label.setStyleSheet("QLabel#quantity_label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.quantity_label.setObjectName("quantity_label")

        self.quantity_textEdit = QtWidgets.QTextEdit(Form)
        self.quantity_textEdit.setGeometry(QtCore.QRect(480, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity_textEdit.setFont(font)
        self.quantity_textEdit.setStyleSheet("QTextEdit#quantity_textEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"border-bottom: 2px solid white;\n"
"}")
        self.quantity_textEdit.setReadOnly(True)
        self.quantity_textEdit.setObjectName("quantity_textEdit")

        self.datasheet_label = QtWidgets.QLabel(Form)
        self.datasheet_label.setGeometry(QtCore.QRect(380, 100, 91, 21))
        self.datasheet_label.setStyleSheet("QLabel#datasheet_label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.datasheet_label.setObjectName("datasheet_label")
        self.datasheet_textEdit = QtWidgets.QTextEdit(Form)
        self.datasheet_textEdit.setGeometry(QtCore.QRect(480, 110, 231, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datasheet_textEdit.setFont(font)
        self.datasheet_textEdit.setStyleSheet("QTextEdit#datasheet_textEdit{\n"
"background-color: rgba(0,0,0,90);\n"
"color: white;\n"
"border: 2px solid rgba(255,255,255,200);\n"
"}")
        self.datasheet_textEdit.setReadOnly(True)
        self.datasheet_textEdit.setObjectName("datasheet_textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.searchLabel.setText(_translate("Form", "Search"))
        self.tip_Label.setText(_translate("Form", "Type"))
        self.SearchConfirm_Button.setText(_translate("Form", "Search"))
        self.model_label.setText(_translate("Form", "Model"))
        self.code_label.setText(_translate("Form", "Code"))
        self.quantity_label.setText(_translate("Form", "Quantity"))
        self.datasheet_label.setText(_translate("Form", "Datasheet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
