# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'see_allWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QWidget
import assets.res.background_rc
import src.db.dataBase

class Ui_Form(QWidget):
    def __init__(self,parent = None):
        super().__init__(parent)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(929, 556)
        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 931, 561))
        self.backgroundLabel.setStyleSheet("QLabel#backgroundLabel{\n"
"background-image: url(:/bg-img/background.png);\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.treeView = QtWidgets.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(20, 20, 891, 511))
        self.treeView.setStyleSheet("QTreeView#treeView{\n"
"background-color: rgba(0,0,0,0);\n"
"border: 1px solid white;\n"
"color: white;\n"
"font-size: 16px;\n"
"} ")
        self.treeView.setObjectName("treeView")

        # Create our model and header
        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["ID","Type","Model","Code","Quantity","Datasheet"])

        # Get data from db
        our_data = src.db.dataBase.getTreeViewModel()

        # Populate the model with the data from db
        for row in our_data:
            items=[QStandardItem(str(field)) for field in row]
            model.appendRow(items)
        self.treeView.setModel(model)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
