# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
import src.db.dataBase
import assets.res.background_rc
from assets.res.background_rc import qt_resource_struct


class Ui_Form(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

    def updateModels(self):
        self.model_comboBox.clear()
        selected_type = self.type_comboBox.currentText()
        models = src.db.dataBase.getMatchingModels(selected_type)
        for model in models:
            self.model_comboBox.addItem(model)
        self.model_comboBox.setCurrentText(" ")
        self.code_comboBox.setCurrentText(" ")

    def updateCodes(self):
        self.code_comboBox.clear()
        selected_type = self.type_comboBox.currentText()
        selected_model = self.model_comboBox.currentText()
        codes = src.db.dataBase.getMatchingCodes(selected_type, selected_model)
        for code in codes:
            self.code_comboBox.addItem(code)
        self.code_comboBox.setCurrentText(" ")

    def updateQuantityToDB(self):
        new_amount = self.amount_spinBox.value()
        new_symbol = self.operation_ComboBox.currentText()
        selected_type = self.type_comboBox.currentText()
        selected_model = self.model_comboBox.currentText()
        selected_code = self.code_comboBox.currentText()
        if new_symbol == "+":
            src.db.dataBase.updateAddFromDB(selected_type, selected_model, selected_code, new_amount)
        elif new_symbol == "-":
            src.db.dataBase.updateSubFromDB(selected_type, selected_model, selected_code, new_amount)
        self.parent().close()

    def setupUi(self, Form):
        Form.setWindowTitle("Components - Update")
        Form.setObjectName("Form")
        Form.setFixedSize(401, 351)

        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 401, 371))
        self.backgroundLabel.setStyleSheet("QLabel#backgroundLabel{\n"
"background-image: url(:/bg-img/background.png);\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")

        self.addLabel = QtWidgets.QLabel(Form)
        self.addLabel.setGeometry(QtCore.QRect(150, 10, 81, 31))
        self.addLabel.setStyleSheet("QLabel#addLabel{\n"
"color: rgba(255,255,255,200);\n"
"font-size: 25px;\n"
"font-family: \"Arial\";\n"
"}")
        self.addLabel.setObjectName("addLabel")

        self.model_Label = QtWidgets.QLabel(Form)
        self.model_Label.setGeometry(QtCore.QRect(50, 110, 51, 21))
        self.model_Label.setStyleSheet("QLabel#model_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.model_Label.setObjectName("model_Label")

        self.tip_Label = QtWidgets.QLabel(Form)
        self.tip_Label.setGeometry(QtCore.QRect(60, 70, 41, 21))
        self.tip_Label.setStyleSheet("QLabel#tip_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.tip_Label.setObjectName("tip_Label")

        self.amount_Label = QtWidgets.QLabel(Form)
        self.amount_Label.setGeometry(QtCore.QRect(40, 190, 61, 21))
        self.amount_Label.setStyleSheet("QLabel#amount_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.amount_Label.setObjectName("amount_Label")

        self.amount_spinBox = QtWidgets.QSpinBox(Form)
        self.amount_spinBox.setGeometry(QtCore.QRect(120, 190, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.amount_spinBox.setFont(font)
        self.amount_spinBox.setStyleSheet("QSpinBox#amount_spinBox{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"border: none;\n"
"font-size: 12px;\n"
"}")
        self.amount_spinBox.setMaximum(999)
        self.amount_spinBox.setObjectName("amount_spinBox")

        self.type_comboBox = QtWidgets.QComboBox(Form)
        self.type_comboBox.setGeometry(QtCore.QRect(120, 60, 221, 31))
        self.type_comboBox.setStyleSheet("QComboBox#type_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color:white;\n"
"font-size: 16px;\n"   
"}")
        self.type_comboBox.setObjectName("type_comboBox")
        # Populate the type box with every unique type from db
        typesList = src.db.dataBase.getAllTypes()
        for type in typesList:
            self.type_comboBox.addItem(type)

        self.model_comboBox = QtWidgets.QComboBox(Form)
        self.model_comboBox.setGeometry(QtCore.QRect(120, 100, 221, 31))
        self.model_comboBox.setStyleSheet("QComboBox#model_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color:white;\n"
"font-size: 16px;\n"   
"}")
        self.model_comboBox.setObjectName("model_comboBox")
        # Populate the model box with every model of the selected type from db
        self.type_comboBox.currentIndexChanged.connect(self.updateModels)

        self.opp_Label = QtWidgets.QLabel(Form)
        self.opp_Label.setGeometry(QtCore.QRect(20, 230, 81, 21))
        self.opp_Label.setStyleSheet("QLabel#opp_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.opp_Label.setObjectName("opp_Label")

        self.operation_ComboBox = QtWidgets.QComboBox(Form)
        self.operation_ComboBox.setGeometry(QtCore.QRect(120, 220, 51, 31))
        self.operation_ComboBox.setStyleSheet("QComboBox#operation_ComboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"padding-bttom: 5px;\n"
"color: white;\n"
"font-size: 17px;\n"
"}")
        self.operation_ComboBox.setObjectName("operation_ComboBox")
        self.operation_ComboBox.addItem("")
        self.operation_ComboBox.addItem("")

        self.UpdateConfirm_Button = QtWidgets.QPushButton(Form)
        self.UpdateConfirm_Button.setGeometry(QtCore.QRect(130, 290, 131, 41))
        self.UpdateConfirm_Button.setStyleSheet("QPushButton#UpdateConfirm_Button{\n"
"background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}\n"
"QPushButton#UpdateConfirm_Button:hover{\n"
"background-color: rgba(0,0,0,125);\n"
"}")
        self.UpdateConfirm_Button.setObjectName("UpdateConfirm_Button")

        self.code_Label = QtWidgets.QLabel(Form)
        self.code_Label.setGeometry(QtCore.QRect(56, 150, 51, 21))
        self.code_Label.setStyleSheet("QLabel#code_Label{\n"
"color: rgba(255,255,255,225);\n"
"font-size: 18px;\n"
"font-family: \"Arial\";\n"
"}")
        self.code_Label.setObjectName("code_Label")

        self.code_comboBox = QtWidgets.QComboBox(Form)
        self.code_comboBox.setGeometry(QtCore.QRect(120, 140, 221, 31))
        self.code_comboBox.setStyleSheet("QComboBox#code_comboBox{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid white;\n"
"color:white;\n"
"font-size: 16px;\n"   
"}")
        self.code_comboBox.setObjectName("code_comboBox")
        # Populate the code box with every cod of the selected type and model from db
        self.model_comboBox.currentIndexChanged.connect(self.updateCodes)

        # When the button is clicked the update is done
        self.UpdateConfirm_Button.clicked.connect(self.updateQuantityToDB)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addLabel.setText(_translate("Form", "Update"))
        self.model_Label.setText(_translate("Form", "Model"))
        self.tip_Label.setText(_translate("Form", "Type"))
        self.amount_Label.setText(_translate("Form", "Amount"))
        self.opp_Label.setText(_translate("Form", "Operation"))
        self.operation_ComboBox.setItemText(0, _translate("Form", "+"))
        self.operation_ComboBox.setItemText(1, _translate("Form", "-"))
        self.UpdateConfirm_Button.setText(_translate("Form", "Update"))
        self.code_Label.setText(_translate("Form", "Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
